const BollywoodData = [
    {
        id: 1,
        imgsrc: "https://images.indianexpress.com/2020/10/mirzapur-2-1200-4.jpg",
        source: "A Amazon Prime Orgignals Series",
        title: "Mirzapur",
        description: "A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.",
        lastRDate: "23 October 2020",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.8cba91ba-d7c6-7327-cbd7-778565d10ce3?autoplay=0&ref_=atv_cf_strg_wb",
    },
    {
        id: 2,
        imgsrc: "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/5a7806efe0ecf5d9a60d7522ae92f644acdbe4cf53a81facca5c714f0c56fbae._V_SX1080_.jpg",
        source: "A Amazon Prime Orgignals Series",
        title: "Panchayat",
        description: "With the rise of an opponent against Pradhan Ji, village politics of Phulera heats up. Unable to stay neutral, Abhishek sticks his neck out for Pradhan's family.",
        lastRDate: "20 May 2022",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.6accc059-e0ec-435a-8af9-1c32b7256303?autoplay=0&ref_=atv_cf_strg_wb",
    },
    {
        id: 3,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFtdECtEdfMVDyRf-X2bKnM0rwhGFTHeNrPg&usqp=CAU",
        source: "A Amazon Prime Orgignals Series",
        title: "Paatal Lok",
        description: "A down and out cop lands the case of a lifetime when four suspects are nabbed in the assassination attempt of a journalist. The pursuit of it leads him to 'Paatal Lok', and to shocking discoveries in the past of the four suspects.",
        lastRDate: "15 May 2020",
        season: "01",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.ecb8e6b7-a43d-5359-5152-4c31c68b977a?autoplay=0&ref_=atv_cf_strg_wb",
    },
    {
        id: 4,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRXARnkz01mJ09CGrGmxbWEenQ1VaSIWTYqA&usqp=CAU",
        source: "A Amazon Prime Orgignals Series",
        title: "Bandish Bandits",
        description: "Indian classical singer Radhe and pop star Tamanna. Despite their contrasting personalities, the two set out together on a journey of self-discovery to see if opposites, though they might attract, can also adapt and go the long haul.",
        lastRDate: "4 August 2020",
        season: "01",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/detail/Bandish-Bandits/0GZ3CSDRPF7ZJ8E9ORRVO8NWRS",
    },
    {
        id: 5,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNc7IPlEF8fG0AeKOPc_fGZboIEoVSXUNj-A&usqp=CAU",
        source: "A Amazon Prime Orgignals Series",
        title: "Made in Heaven",
        description: "It is the story of two wedding planners in Delhi, where tradition jostles with modern aspirations against the backdrop of big fat Indian weddings revealing many secrets and lies.",
        lastRDate: "8 March 2019",
        season: "01",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.a4b49e66-44f7-3483-e10a-5542fdd911ba?autoplay=0&ref_=atv_cf_strg_wb",
    },
    {
        id: 6,
        imgsrc: "https://www.koimoi.com/wp-content/new-galleries/2020/03/20200320_022710_0000.png",
        source: "A Hotstar Specials Orgignals Series",
        title: "Special OPS",
        description: "The story through the eyes of Himmat Singh is based on the inspiration was taken from Nineteen Years of nationally significant events, several espionage missions were undertaken by India in the last two decades.",
        lastRDate: "12 November 2021",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.hotstar.com/ca/tv/special-ops/1260022894",
    },
    {
        id: 7,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGCF-5I8sZxlgHMeIVK0-svDQREQbV47jq4g&usqp=CAU",
        source: "A Hotstar Specials Orgignals Series",
        title: "Aarya",
        description: "When her world suddenly turns upside down, will Aarya become the very thing she hated?How far will she go to survive and protect her family?",
        lastRDate: "10 December 2021",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.hotstar.com/in/tv/aarya/1260028094",
    },
    {
        id: 8,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDnOpl-IVOsjkP83rORkoKNPFSFeeG39NZhA&usqp=CAU",
        source: "A Netflix Original Movies",
        title: "Sacred Games",
        description: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
        lastRDate: "15 August 2019",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.netflix.com/in/title/80115328?source=35",
    },
    {
        id: 9,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVarzH6OI0HiD294dC5F9-xPOlwsLsA0dr_Q&usqp=CAU",
        source: "A Netflix Original Movies",
        title: "Kota Factory",
        description: "Dedicated to Shrimati SL Loney ji, Shri Irodov ji and Maanniya HC Verma ji, 'Kota Factory' is TVF's latest original. India's first 'Black and White' show highlights the problems present day IIT-JEE aspirants face in their day-to-day lives.",
        lastRDate: "24 September 2022",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.netflix.com/in/title/81249783?source=35",
    },
    {
        id: 10,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsfRAqDW37KXD6qvJyMi2iVAiMpEFjBemw-Q&usqp=CAU",
        source: "A Netflix Original Movies",
        title: "Criminal Justice",
        description: "Sex, drugs and a gruesome murder. An edgy one night stand turns into a nightmare for Aditya, when he wakes up with blood on his hands. The evidence is stacked against him, but he doesn't remember the grisly crime. Is he guilty or not ?",
        lastRDate: "24 December 2020",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.hotstar.com/in/tv/criminal-justice/1260004267?utm_source=gwa",
    },
    {
        id: 11,
        imgsrc: "https://images.indianexpress.com/2020/10/scam-1992-review-1200.jpg",
        source: "A SonyLiv Orgignals Series",
        title: "Scam 1992: The Harshad Mehta Story",
        description: "Scam is about the major scandals that shook India and are remembered as some of the most notorious crimes of the country. Set in 1980's and 90's Bombay, Scam 1992 follows the life of Harshad Mehta - the infamous “Bachchan of BSE”. It was a rags-to-riches story till financial journalist Sucheta Dalal exposed Harshad as the man behind India's biggest financial scam. After his arrest, the stock market crashed and countless Indians lost all savings. For the first time, the CBI was compelled to launch an investigation into a financial crime. A corrupt financial system was revealed. Harshad eventually died in custody.",
        lastRDate: "09 October 2020",
        season: "01",
        author: "Vijayant Joshi",
        updated: "06 Aug 2022",
        link: "https://www.sonyliv.com/shows/scam-1992-the-harshad-mehta-story-marathi-1700000845?utm_source=Google&utm_medium=WatchNow&utm_campaign=1700000845",
    },
    {
        id: 12,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3SyOH1F2IY4WYQvVqzYvEAZTuNdU7IfLfBQ&usqp=CAU",
        source: "A Voot Select Orgignals Series",
        title: "Asur: Welcome to Your Dark Side",
        description: "A unique crime thriller that pits two opposing worlds against each other. The less explored, intricate world of forensic science and the deep mysticism of ancient Indian Mythology.",
        lastRDate: "2 March 2020",
        season: "01",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.voot.com/shows/asur/121993?utm_source=google_web&utm_medium=watchaction",
    },
    {
        id: 13,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRkxD2MuSzA3T5JDEVgUabkEQHDGeVSZ9nkQ&usqp=CAU",
        source: "A TVF Play Orgignals Series",
        title: "Flames",
        description: "A teenage romance from The Timeliners that aims straight from the heart. This web-series is the story of a young romance unfolding as a chemical reaction.",
        lastRDate: "End of December 2021",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://tvfplay.com/show/flames-by-the-timeliners/266",
    },
    {
        id: 14,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7ItV9PHufrtx9FS9OuV0BGK206iwqDmhpcg&usqp=CAU",
        source: "A Amazon Prime Orgignals Series",
        title: "The Family Man",
        description: "A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also needs to keep his family safe from his secret job",
        lastRDate: "4 June 2021",
        season: "01, 02",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.22bb90dc-bcd5-9f15-b502-48b198b5b199?autoplay=0&ref_=atv_cf_strg_wb",
    },
    {
        id: 15,
        imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiWvYYv7o5zlgcaed9FpQSxNuVm4H16zinzA&usqp=CAU",
        source: "A Amazon Prime Orgignals Series",
        title: "Breathe, Breathe: Into the Shadows",
        description: "This series just asks one question - how far will you go to protect the one you love. Two desperate and driven men must engage in the ultimate cat and mouse game to save the one they love.",
        lastRDate: "26 January 2018, 10 July 2020",
        season: "01, 01",
        author: "Vijayant Joshi",
        updated: "07 Aug 2022",
        link: "https://www.primevideo.com/dp/amzn1.dv.gti.44b97710-b980-450a-8c81-9ca4df980e2b?autoplay=0&ref_=atv_cf_strg_wb",
    }
]

export default BollywoodData;